// <auto-generated />
using System;
using Letsgo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Letsgo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260504183158_AggiuntoNuovoCampo")]
    partial class AggiuntoNuovoCampo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Letsgo.Models.DestinazioneArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aeroporto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaGeografica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DestinazioniAree");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aeroporto = "FCO",
                            AreaGeografica = "Europa",
                            Citta = "Roma"
                        },
                        new
                        {
                            Id = 2,
                            Aeroporto = "MXP",
                            AreaGeografica = "Europa",
                            Citta = "Milano"
                        },
                        new
                        {
                            Id = 3,
                            Aeroporto = "CDG",
                            AreaGeografica = "Europa",
                            Citta = "Parigi"
                        },
                        new
                        {
                            Id = 4,
                            Aeroporto = "LHR",
                            AreaGeografica = "Europa",
                            Citta = "Londra"
                        },
                        new
                        {
                            Id = 5,
                            Aeroporto = "MAD",
                            AreaGeografica = "Europa",
                            Citta = "Madrid"
                        },
                        new
                        {
                            Id = 6,
                            Aeroporto = "BER",
                            AreaGeografica = "Europa",
                            Citta = "Berlino"
                        },
                        new
                        {
                            Id = 7,
                            Aeroporto = "AMS",
                            AreaGeografica = "Europa",
                            Citta = "Amsterdam"
                        },
                        new
                        {
                            Id = 8,
                            Aeroporto = "VIE",
                            AreaGeografica = "Europa",
                            Citta = "Vienna"
                        },
                        new
                        {
                            Id = 9,
                            Aeroporto = "LIS",
                            AreaGeografica = "Europa",
                            Citta = "Lisbona"
                        },
                        new
                        {
                            Id = 10,
                            Aeroporto = "ATH",
                            AreaGeografica = "Europa",
                            Citta = "Atene"
                        },
                        new
                        {
                            Id = 11,
                            Aeroporto = "HND",
                            AreaGeografica = "Asia",
                            Citta = "Tokyo"
                        },
                        new
                        {
                            Id = 12,
                            Aeroporto = "PEK",
                            AreaGeografica = "Asia",
                            Citta = "Pechino"
                        },
                        new
                        {
                            Id = 13,
                            Aeroporto = "BKK",
                            AreaGeografica = "Asia",
                            Citta = "Bangkok"
                        },
                        new
                        {
                            Id = 14,
                            Aeroporto = "SIN",
                            AreaGeografica = "Asia",
                            Citta = "Singapore"
                        },
                        new
                        {
                            Id = 15,
                            Aeroporto = "DXB",
                            AreaGeografica = "Asia",
                            Citta = "Dubai"
                        },
                        new
                        {
                            Id = 16,
                            Aeroporto = "ICN",
                            AreaGeografica = "Asia",
                            Citta = "Seoul"
                        },
                        new
                        {
                            Id = 17,
                            Aeroporto = "BOM",
                            AreaGeografica = "Asia",
                            Citta = "Mumbai"
                        },
                        new
                        {
                            Id = 18,
                            Aeroporto = "HKG",
                            AreaGeografica = "Asia",
                            Citta = "Hong Kong"
                        },
                        new
                        {
                            Id = 19,
                            Aeroporto = "KUL",
                            AreaGeografica = "Asia",
                            Citta = "Kuala Lumpur"
                        },
                        new
                        {
                            Id = 20,
                            Aeroporto = "TPE",
                            AreaGeografica = "Asia",
                            Citta = "Taipei"
                        },
                        new
                        {
                            Id = 21,
                            Aeroporto = "JFK",
                            AreaGeografica = "America",
                            Citta = "New York"
                        },
                        new
                        {
                            Id = 22,
                            Aeroporto = "LAX",
                            AreaGeografica = "America",
                            Citta = "Los Angeles"
                        },
                        new
                        {
                            Id = 23,
                            Aeroporto = "MIA",
                            AreaGeografica = "America",
                            Citta = "Miami"
                        },
                        new
                        {
                            Id = 24,
                            Aeroporto = "YYZ",
                            AreaGeografica = "America",
                            Citta = "Toronto"
                        },
                        new
                        {
                            Id = 25,
                            Aeroporto = "GRU",
                            AreaGeografica = "America",
                            Citta = "San Paolo"
                        },
                        new
                        {
                            Id = 26,
                            Aeroporto = "EZE",
                            AreaGeografica = "America",
                            Citta = "Buenos Aires"
                        },
                        new
                        {
                            Id = 27,
                            Aeroporto = "MEX",
                            AreaGeografica = "America",
                            Citta = "Città del Messico"
                        },
                        new
                        {
                            Id = 28,
                            Aeroporto = "ORD",
                            AreaGeografica = "America",
                            Citta = "Chicago"
                        },
                        new
                        {
                            Id = 29,
                            Aeroporto = "SFO",
                            AreaGeografica = "America",
                            Citta = "San Francisco"
                        },
                        new
                        {
                            Id = 30,
                            Aeroporto = "LIM",
                            AreaGeografica = "America",
                            Citta = "Lima"
                        },
                        new
                        {
                            Id = 31,
                            Aeroporto = "CAI",
                            AreaGeografica = "Africa",
                            Citta = "Il Cairo"
                        },
                        new
                        {
                            Id = 32,
                            Aeroporto = "RAK",
                            AreaGeografica = "Africa",
                            Citta = "Marrakech"
                        },
                        new
                        {
                            Id = 33,
                            Aeroporto = "CPT",
                            AreaGeografica = "Africa",
                            Citta = "Città del Capo"
                        },
                        new
                        {
                            Id = 34,
                            Aeroporto = "JNB",
                            AreaGeografica = "Africa",
                            Citta = "Johannesburg"
                        },
                        new
                        {
                            Id = 35,
                            Aeroporto = "NBO",
                            AreaGeografica = "Africa",
                            Citta = "Nairobi"
                        },
                        new
                        {
                            Id = 36,
                            Aeroporto = "TUN",
                            AreaGeografica = "Africa",
                            Citta = "Tunisi"
                        },
                        new
                        {
                            Id = 37,
                            Aeroporto = "CMN",
                            AreaGeografica = "Africa",
                            Citta = "Casablanca"
                        },
                        new
                        {
                            Id = 38,
                            Aeroporto = "ADD",
                            AreaGeografica = "Africa",
                            Citta = "Addis Abeba"
                        },
                        new
                        {
                            Id = 39,
                            Aeroporto = "DSS",
                            AreaGeografica = "Africa",
                            Citta = "Dakar"
                        },
                        new
                        {
                            Id = 40,
                            Aeroporto = "ACC",
                            AreaGeografica = "Africa",
                            Citta = "Accra"
                        },
                        new
                        {
                            Id = 41,
                            Aeroporto = "SYD",
                            AreaGeografica = "Oceania",
                            Citta = "Sydney"
                        },
                        new
                        {
                            Id = 42,
                            Aeroporto = "MEL",
                            AreaGeografica = "Oceania",
                            Citta = "Melbourne"
                        },
                        new
                        {
                            Id = 43,
                            Aeroporto = "AKL",
                            AreaGeografica = "Oceania",
                            Citta = "Auckland"
                        },
                        new
                        {
                            Id = 44,
                            Aeroporto = "BNE",
                            AreaGeografica = "Oceania",
                            Citta = "Brisbane"
                        },
                        new
                        {
                            Id = 45,
                            Aeroporto = "PER",
                            AreaGeografica = "Oceania",
                            Citta = "Perth"
                        },
                        new
                        {
                            Id = 46,
                            Aeroporto = "WLG",
                            AreaGeografica = "Oceania",
                            Citta = "Wellington"
                        },
                        new
                        {
                            Id = 47,
                            Aeroporto = "CHC",
                            AreaGeografica = "Oceania",
                            Citta = "Christchurch"
                        },
                        new
                        {
                            Id = 48,
                            Aeroporto = "ADL",
                            AreaGeografica = "Oceania",
                            Citta = "Adelaide"
                        },
                        new
                        {
                            Id = 49,
                            Aeroporto = "NAN",
                            AreaGeografica = "Oceania",
                            Citta = "Nadi"
                        },
                        new
                        {
                            Id = 50,
                            Aeroporto = "PPT",
                            AreaGeografica = "Oceania",
                            Citta = "Papeete"
                        });
                });

            modelBuilder.Entity("Letsgo.Models.DestinazioneSalvata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AeroportoDestinazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AeroportoPartenza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaGeografica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CittaDestinazione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPartenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRitorno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSalvataggio")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrizioneMeteo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurataTotaleMinuti")
                        .HasColumnType("int");

                    b.Property<string>("EmailUtente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUtente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Prezzo")
                        .HasColumnType("int");

                    b.Property<double?>("Temperatura")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DestinazioniSalvate");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
